version: 2.1
orbs:
  node: circleci/node@4.1
workflows:
  node-tests: 
    jobs:
      - node/test
      # For running simple node tests, you could optionally use the node/test job from the orb to replicate and replace the job above in fewer lines.
      # - node/test
